# Generated by Django 3.1.5 on 2021-02-06 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0004_auto_20210120_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='publicado_comentario',
            field=models.BooleanField(default=True, verbose_name='Publicado'),
        ),
    ]
