# Generated by Django 3.1.5 on 2021-02-24 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0005_auto_20210206_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='email_comentario',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='nome_comentario',
        ),
    ]
